# coding: utf-8

"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    OpenAPI spec version: 8.52.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import here_public_transit_api
from here_public_transit_api.models.all_of_base_place_original_location import AllOfBasePlaceOriginalLocation  # noqa: E501
from here_public_transit_api.rest import ApiException


class TestAllOfBasePlaceOriginalLocation(unittest.TestCase):
    """AllOfBasePlaceOriginalLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfBasePlaceOriginalLocation(self):
        """Test AllOfBasePlaceOriginalLocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = here_public_transit_api.models.all_of_base_place_original_location.AllOfBasePlaceOriginalLocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
