# coding: utf-8

"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    OpenAPI spec version: 8.52.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import here_public_transit_api
from here_public_transit_api.models.parking_lot_place import ParkingLotPlace  # noqa: E501
from here_public_transit_api.rest import ApiException


class TestParkingLotPlace(unittest.TestCase):
    """ParkingLotPlace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParkingLotPlace(self):
        """Test ParkingLotPlace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = here_public_transit_api.models.parking_lot_place.ParkingLotPlace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
