# coding: utf-8

"""
    Public Transit API

    Public Transit is a set of three REST APIs that provides public transit routing information and public transit stations information available within an area or for a given station.   # noqa: E501

    OpenAPI spec version: 8.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import here_public_transit_api
from here_public_transit_api.models.all_of_charging_connector_attributes_supply_type import AllOfChargingConnectorAttributesSupplyType  # noqa: E501
from here_public_transit_api.rest import ApiException


class TestAllOfChargingConnectorAttributesSupplyType(unittest.TestCase):
    """AllOfChargingConnectorAttributesSupplyType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfChargingConnectorAttributesSupplyType(self):
        """Test AllOfChargingConnectorAttributesSupplyType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = here_public_transit_api.models.all_of_charging_connector_attributes_supply_type.AllOfChargingConnectorAttributesSupplyType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
