# coding: utf-8

"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    OpenAPI spec version: 8.52.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import here_public_transit_api
from here_public_transit_api.models.all_of_range_price_unit import AllOfRangePriceUnit  # noqa: E501
from here_public_transit_api.rest import ApiException


class TestAllOfRangePriceUnit(unittest.TestCase):
    """AllOfRangePriceUnit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfRangePriceUnit(self):
        """Test AllOfRangePriceUnit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = here_public_transit_api.models.all_of_range_price_unit.AllOfRangePriceUnit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
