# coding: utf-8

"""
    Public Transit API

    Public Transit is a set of three REST APIs that provides public transit routing information and public transit stations information available within an area or for a given station.   # noqa: E501

    OpenAPI spec version: 8.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import here_public_transit_api
from here_public_transit_api.models.transit_mode_output import TransitModeOutput  # noqa: E501
from here_public_transit_api.rest import ApiException


class TestTransitModeOutput(unittest.TestCase):
    """TransitModeOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransitModeOutput(self):
        """Test TransitModeOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = here_public_transit_api.models.transit_mode_output.TransitModeOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
