# coding: utf-8

"""
    Public Transit API

    Public Transit is a set of three REST APIs that provides public transit routing information and public transit stations information available within an area or for a given station.   # noqa: E501

    OpenAPI spec version: 8.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DepartureDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time': 'AllOfDepartureDetailsTime',
        'delay': 'DepartureDelay',
        'status': 'DepartureStatus',
        'platform': 'DeparturePlatform',
        'transport': 'TransitTransport',
        'agency': 'Agency'
    }

    attribute_map = {
        'time': 'time',
        'delay': 'delay',
        'status': 'status',
        'platform': 'platform',
        'transport': 'transport',
        'agency': 'agency'
    }

    def __init__(self, time=None, delay=None, status=None, platform=None, transport=None, agency=None):  # noqa: E501
        """DepartureDetails - a model defined in Swagger"""  # noqa: E501
        self._time = None
        self._delay = None
        self._status = None
        self._platform = None
        self._transport = None
        self._agency = None
        self.discriminator = None
        self.time = time
        if delay is not None:
            self.delay = delay
        if status is not None:
            self.status = status
        if platform is not None:
            self.platform = platform
        self.transport = transport
        if agency is not None:
            self.agency = agency

    @property
    def time(self):
        """Gets the time of this DepartureDetails.  # noqa: E501

        Expected time of the departure of the event. Format is **RFC 3339**, section 5.6 as defined by `date-time`.  # noqa: E501

        :return: The time of this DepartureDetails.  # noqa: E501
        :rtype: AllOfDepartureDetailsTime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this DepartureDetails.

        Expected time of the departure of the event. Format is **RFC 3339**, section 5.6 as defined by `date-time`.  # noqa: E501

        :param time: The time of this DepartureDetails.  # noqa: E501
        :type: AllOfDepartureDetailsTime
        """
        if time is None:
            raise ValueError("Invalid value for `time`, must not be `None`")  # noqa: E501

        self._time = time

    @property
    def delay(self):
        """Gets the delay of this DepartureDetails.  # noqa: E501


        :return: The delay of this DepartureDetails.  # noqa: E501
        :rtype: DepartureDelay
        """
        return self._delay

    @delay.setter
    def delay(self, delay):
        """Sets the delay of this DepartureDetails.


        :param delay: The delay of this DepartureDetails.  # noqa: E501
        :type: DepartureDelay
        """

        self._delay = delay

    @property
    def status(self):
        """Gets the status of this DepartureDetails.  # noqa: E501


        :return: The status of this DepartureDetails.  # noqa: E501
        :rtype: DepartureStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DepartureDetails.


        :param status: The status of this DepartureDetails.  # noqa: E501
        :type: DepartureStatus
        """

        self._status = status

    @property
    def platform(self):
        """Gets the platform of this DepartureDetails.  # noqa: E501


        :return: The platform of this DepartureDetails.  # noqa: E501
        :rtype: DeparturePlatform
        """
        return self._platform

    @platform.setter
    def platform(self, platform):
        """Sets the platform of this DepartureDetails.


        :param platform: The platform of this DepartureDetails.  # noqa: E501
        :type: DeparturePlatform
        """

        self._platform = platform

    @property
    def transport(self):
        """Gets the transport of this DepartureDetails.  # noqa: E501


        :return: The transport of this DepartureDetails.  # noqa: E501
        :rtype: TransitTransport
        """
        return self._transport

    @transport.setter
    def transport(self, transport):
        """Sets the transport of this DepartureDetails.


        :param transport: The transport of this DepartureDetails.  # noqa: E501
        :type: TransitTransport
        """
        if transport is None:
            raise ValueError("Invalid value for `transport`, must not be `None`")  # noqa: E501

        self._transport = transport

    @property
    def agency(self):
        """Gets the agency of this DepartureDetails.  # noqa: E501


        :return: The agency of this DepartureDetails.  # noqa: E501
        :rtype: Agency
        """
        return self._agency

    @agency.setter
    def agency(self, agency):
        """Sets the agency of this DepartureDetails.


        :param agency: The agency of this DepartureDetails.  # noqa: E501
        :type: Agency
        """

        self._agency = agency

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DepartureDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DepartureDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
