# coding: utf-8

"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    OpenAPI spec version: 8.52.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ErrorResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'status': 'int',
        'code': 'str',
        'cause': 'str',
        'action': 'str',
        'correlation_id': 'str'
    }

    attribute_map = {
        'title': 'title',
        'status': 'status',
        'code': 'code',
        'cause': 'cause',
        'action': 'action',
        'correlation_id': 'correlationId'
    }

    def __init__(self, title=None, status=None, code=None, cause=None, action=None, correlation_id=None):  # noqa: E501
        """ErrorResponse - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._status = None
        self._code = None
        self._cause = None
        self._action = None
        self._correlation_id = None
        self.discriminator = None
        self.title = title
        self.status = status
        self.code = code
        self.cause = cause
        self.action = action
        self.correlation_id = correlation_id

    @property
    def title(self):
        """Gets the title of this ErrorResponse.  # noqa: E501

        Human-readable error description  # noqa: E501

        :return: The title of this ErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this ErrorResponse.

        Human-readable error description  # noqa: E501

        :param title: The title of this ErrorResponse.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def status(self):
        """Gets the status of this ErrorResponse.  # noqa: E501

        HTTP status code  # noqa: E501

        :return: The status of this ErrorResponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ErrorResponse.

        HTTP status code  # noqa: E501

        :param status: The status of this ErrorResponse.  # noqa: E501
        :type: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def code(self):
        """Gets the code of this ErrorResponse.  # noqa: E501

        Error code.  All error codes start with \"`E60`\".   # noqa: E501

        :return: The code of this ErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ErrorResponse.

        Error code.  All error codes start with \"`E60`\".   # noqa: E501

        :param code: The code of this ErrorResponse.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def cause(self):
        """Gets the cause of this ErrorResponse.  # noqa: E501

        Human-readable explanation for the error  # noqa: E501

        :return: The cause of this ErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._cause

    @cause.setter
    def cause(self, cause):
        """Sets the cause of this ErrorResponse.

        Human-readable explanation for the error  # noqa: E501

        :param cause: The cause of this ErrorResponse.  # noqa: E501
        :type: str
        """
        if cause is None:
            raise ValueError("Invalid value for `cause`, must not be `None`")  # noqa: E501

        self._cause = cause

    @property
    def action(self):
        """Gets the action of this ErrorResponse.  # noqa: E501

        Human-readable description of the action that can be taken to correct the error  # noqa: E501

        :return: The action of this ErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this ErrorResponse.

        Human-readable description of the action that can be taken to correct the error  # noqa: E501

        :param action: The action of this ErrorResponse.  # noqa: E501
        :type: str
        """
        if action is None:
            raise ValueError("Invalid value for `action`, must not be `None`")  # noqa: E501

        self._action = action

    @property
    def correlation_id(self):
        """Gets the correlation_id of this ErrorResponse.  # noqa: E501

        Auto-generated id that univocally identifies the request  # noqa: E501

        :return: The correlation_id of this ErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._correlation_id

    @correlation_id.setter
    def correlation_id(self, correlation_id):
        """Sets the correlation_id of this ErrorResponse.

        Auto-generated id that univocally identifies the request  # noqa: E501

        :param correlation_id: The correlation_id of this ErrorResponse.  # noqa: E501
        :type: str
        """
        if correlation_id is None:
            raise ValueError("Invalid value for `correlation_id`, must not be `None`")  # noqa: E501

        self._correlation_id = correlation_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ErrorResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ErrorResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
