# coding: utf-8

"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    OpenAPI spec version: 8.52.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MatchTraceVia(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'index': 'int',
        'stop_duration': 'AllOfMatchTraceViaStopDuration'
    }

    attribute_map = {
        'index': 'index',
        'stop_duration': 'stopDuration'
    }

    def __init__(self, index=None, stop_duration=None):  # noqa: E501
        """MatchTraceVia - a model defined in Swagger"""  # noqa: E501
        self._index = None
        self._stop_duration = None
        self.discriminator = None
        self.index = index
        if stop_duration is not None:
            self.stop_duration = stop_duration

    @property
    def index(self):
        """Gets the index of this MatchTraceVia.  # noqa: E501

        Index of the corresponding trace point  # noqa: E501

        :return: The index of this MatchTraceVia.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this MatchTraceVia.

        Index of the corresponding trace point  # noqa: E501

        :param index: The index of this MatchTraceVia.  # noqa: E501
        :type: int
        """
        if index is None:
            raise ValueError("Invalid value for `index`, must not be `None`")  # noqa: E501

        self._index = index

    @property
    def stop_duration(self):
        """Gets the stop_duration of this MatchTraceVia.  # noqa: E501

        Desired duration for the stop, in seconds  # noqa: E501

        :return: The stop_duration of this MatchTraceVia.  # noqa: E501
        :rtype: AllOfMatchTraceViaStopDuration
        """
        return self._stop_duration

    @stop_duration.setter
    def stop_duration(self, stop_duration):
        """Sets the stop_duration of this MatchTraceVia.

        Desired duration for the stop, in seconds  # noqa: E501

        :param stop_duration: The stop_duration of this MatchTraceVia.  # noqa: E501
        :type: AllOfMatchTraceViaStopDuration
        """

        self._stop_duration = stop_duration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MatchTraceVia, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MatchTraceVia):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
