# coding: utf-8

"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    OpenAPI spec version: 8.52.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MaxSpeedOnSegmentPostInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'segment': 'str',
        'speed': 'float'
    }

    attribute_map = {
        'segment': 'segment',
        'speed': 'speed'
    }

    def __init__(self, segment=None, speed=None):  # noqa: E501
        """MaxSpeedOnSegmentPostInner - a model defined in Swagger"""  # noqa: E501
        self._segment = None
        self._speed = None
        self.discriminator = None
        if segment is not None:
            self.segment = segment
        if speed is not None:
            self.speed = speed

    @property
    def segment(self):
        """Gets the segment of this MaxSpeedOnSegmentPostInner.  # noqa: E501

        Identifier of the segment with restrictions on maximum `baseSpeed`.  Each entry has the following structure: `{segmentId}(#{direction})?`   # noqa: E501

        :return: The segment of this MaxSpeedOnSegmentPostInner.  # noqa: E501
        :rtype: str
        """
        return self._segment

    @segment.setter
    def segment(self, segment):
        """Sets the segment of this MaxSpeedOnSegmentPostInner.

        Identifier of the segment with restrictions on maximum `baseSpeed`.  Each entry has the following structure: `{segmentId}(#{direction})?`   # noqa: E501

        :param segment: The segment of this MaxSpeedOnSegmentPostInner.  # noqa: E501
        :type: str
        """

        self._segment = segment

    @property
    def speed(self):
        """Gets the speed of this MaxSpeedOnSegmentPostInner.  # noqa: E501

        Maximum `baseSpeed` on segment in m/s.   # noqa: E501

        :return: The speed of this MaxSpeedOnSegmentPostInner.  # noqa: E501
        :rtype: float
        """
        return self._speed

    @speed.setter
    def speed(self, speed):
        """Sets the speed of this MaxSpeedOnSegmentPostInner.

        Maximum `baseSpeed` on segment in m/s.   # noqa: E501

        :param speed: The speed of this MaxSpeedOnSegmentPostInner.  # noqa: E501
        :type: float
        """

        self._speed = speed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MaxSpeedOnSegmentPostInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MaxSpeedOnSegmentPostInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
