# coding: utf-8

"""
    Public Transit API

    Public Transit is a set of three REST APIs that provides public transit routing information and public transit stations information available within an area or for a given station.   # noqa: E501

    OpenAPI spec version: 8.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StationInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'notices': 'list[Notice]',
        'place': 'AllOfStationInfoPlace',
        'transports': 'list[TransitTransport]',
        'access_points': 'list[AccessPointPlace]'
    }

    attribute_map = {
        'notices': 'notices',
        'place': 'place',
        'transports': 'transports',
        'access_points': 'accessPoints'
    }

    def __init__(self, notices=None, place=None, transports=None, access_points=None):  # noqa: E501
        """StationInfo - a model defined in Swagger"""  # noqa: E501
        self._notices = None
        self._place = None
        self._transports = None
        self._access_points = None
        self.discriminator = None
        if notices is not None:
            self.notices = notices
        self.place = place
        if transports is not None:
            self.transports = transports
        if access_points is not None:
            self.access_points = access_points

    @property
    def notices(self):
        """Gets the notices of this StationInfo.  # noqa: E501

        Contains a list of issues related to this station.  Follows a list of possible notice codes:  * `noDepartureInfo`: Departure information is unavailable or inaccurate for this station/stop.   # noqa: E501

        :return: The notices of this StationInfo.  # noqa: E501
        :rtype: list[Notice]
        """
        return self._notices

    @notices.setter
    def notices(self, notices):
        """Sets the notices of this StationInfo.

        Contains a list of issues related to this station.  Follows a list of possible notice codes:  * `noDepartureInfo`: Departure information is unavailable or inaccurate for this station/stop.   # noqa: E501

        :param notices: The notices of this StationInfo.  # noqa: E501
        :type: list[Notice]
        """

        self._notices = notices

    @property
    def place(self):
        """Gets the place of this StationInfo.  # noqa: E501

        Information about a station or stop.  # noqa: E501

        :return: The place of this StationInfo.  # noqa: E501
        :rtype: AllOfStationInfoPlace
        """
        return self._place

    @place.setter
    def place(self, place):
        """Sets the place of this StationInfo.

        Information about a station or stop.  # noqa: E501

        :param place: The place of this StationInfo.  # noqa: E501
        :type: AllOfStationInfoPlace
        """
        if place is None:
            raise ValueError("Invalid value for `place`, must not be `None`")  # noqa: E501

        self._place = place

    @property
    def transports(self):
        """Gets the transports of this StationInfo.  # noqa: E501

        A list of transit services.  # noqa: E501

        :return: The transports of this StationInfo.  # noqa: E501
        :rtype: list[TransitTransport]
        """
        return self._transports

    @transports.setter
    def transports(self, transports):
        """Sets the transports of this StationInfo.

        A list of transit services.  # noqa: E501

        :param transports: The transports of this StationInfo.  # noqa: E501
        :type: list[TransitTransport]
        """

        self._transports = transports

    @property
    def access_points(self):
        """Gets the access_points of this StationInfo.  # noqa: E501

        A list of access points  # noqa: E501

        :return: The access_points of this StationInfo.  # noqa: E501
        :rtype: list[AccessPointPlace]
        """
        return self._access_points

    @access_points.setter
    def access_points(self, access_points):
        """Sets the access_points of this StationInfo.

        A list of access points  # noqa: E501

        :param access_points: The access_points of this StationInfo.  # noqa: E501
        :type: list[AccessPointPlace]
        """

        self._access_points = access_points

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StationInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StationInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
