# coding: utf-8

"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    OpenAPI spec version: 8.52.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Taxi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'allow_drive_through_taxi_roads': 'bool'
    }

    attribute_map = {
        'allow_drive_through_taxi_roads': 'allowDriveThroughTaxiRoads'
    }

    def __init__(self, allow_drive_through_taxi_roads=True):  # noqa: E501
        """Taxi - a model defined in Swagger"""  # noqa: E501
        self._allow_drive_through_taxi_roads = None
        self.discriminator = None
        if allow_drive_through_taxi_roads is not None:
            self.allow_drive_through_taxi_roads = allow_drive_through_taxi_roads

    @property
    def allow_drive_through_taxi_roads(self):
        """Gets the allow_drive_through_taxi_roads of this Taxi.  # noqa: E501

        Specifies if a vehicle is allowed to drive through taxi-only roads and lanes. Even if this option is set to false, the vehicle is still allowed on taxi-only roads at the start of the route and at the destination.  **Alpha**: This parameter may not be stable and is subject to change.   # noqa: E501

        :return: The allow_drive_through_taxi_roads of this Taxi.  # noqa: E501
        :rtype: bool
        """
        return self._allow_drive_through_taxi_roads

    @allow_drive_through_taxi_roads.setter
    def allow_drive_through_taxi_roads(self, allow_drive_through_taxi_roads):
        """Sets the allow_drive_through_taxi_roads of this Taxi.

        Specifies if a vehicle is allowed to drive through taxi-only roads and lanes. Even if this option is set to false, the vehicle is still allowed on taxi-only roads at the start of the route and at the destination.  **Alpha**: This parameter may not be stable and is subject to change.   # noqa: E501

        :param allow_drive_through_taxi_roads: The allow_drive_through_taxi_roads of this Taxi.  # noqa: E501
        :type: bool
        """

        self._allow_drive_through_taxi_roads = allow_drive_through_taxi_roads

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Taxi, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Taxi):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
