# coding: utf-8

"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    OpenAPI spec version: 8.52.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TollCountrySummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'country_code': 'CountryCode',
        'price': 'FarePrice'
    }

    attribute_map = {
        'country_code': 'countryCode',
        'price': 'price'
    }

    def __init__(self, country_code=None, price=None):  # noqa: E501
        """TollCountrySummary - a model defined in Swagger"""  # noqa: E501
        self._country_code = None
        self._price = None
        self.discriminator = None
        if country_code is not None:
            self.country_code = country_code
        if price is not None:
            self.price = price

    @property
    def country_code(self):
        """Gets the country_code of this TollCountrySummary.  # noqa: E501


        :return: The country_code of this TollCountrySummary.  # noqa: E501
        :rtype: CountryCode
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this TollCountrySummary.


        :param country_code: The country_code of this TollCountrySummary.  # noqa: E501
        :type: CountryCode
        """

        self._country_code = country_code

    @property
    def price(self):
        """Gets the price of this TollCountrySummary.  # noqa: E501


        :return: The price of this TollCountrySummary.  # noqa: E501
        :rtype: FarePrice
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this TollCountrySummary.


        :param price: The price of this TollCountrySummary.  # noqa: E501
        :type: FarePrice
        """

        self._price = price

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TollCountrySummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TollCountrySummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
