# coding: utf-8

"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    OpenAPI spec version: 8.52.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TollSystem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'ref': 'str'
    }

    attribute_map = {
        'name': 'name',
        'ref': 'ref'
    }

    def __init__(self, name=None, ref=None):  # noqa: E501
        """TollSystem - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._ref = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if ref is not None:
            self.ref = ref

    @property
    def name(self):
        """Gets the name of this TollSystem.  # noqa: E501

        Name of this toll system   # noqa: E501

        :return: The name of this TollSystem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TollSystem.

        Name of this toll system   # noqa: E501

        :param name: The name of this TollSystem.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def ref(self):
        """Gets the ref of this TollSystem.  # noqa: E501

        Internal identification of this toll system. Will be replaced in the future by an hrn identifier.   # noqa: E501

        :return: The ref of this TollSystem.  # noqa: E501
        :rtype: str
        """
        return self._ref

    @ref.setter
    def ref(self, ref):
        """Sets the ref of this TollSystem.

        Internal identification of this toll system. Will be replaced in the future by an hrn identifier.   # noqa: E501

        :param ref: The ref of this TollSystem.  # noqa: E501
        :type: str
        """

        self._ref = ref

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TollSystem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TollSystem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
