# coding: utf-8

"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    OpenAPI spec version: 8.52.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VehicleDeparture(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time': 'AllOfVehicleDepartureTime',
        'place': 'VehiclePlace',
        'charge': 'float'
    }

    attribute_map = {
        'time': 'time',
        'place': 'place',
        'charge': 'charge'
    }

    def __init__(self, time=None, place=None, charge=None):  # noqa: E501
        """VehicleDeparture - a model defined in Swagger"""  # noqa: E501
        self._time = None
        self._place = None
        self._charge = None
        self.discriminator = None
        if time is not None:
            self.time = time
        self.place = place
        if charge is not None:
            self.charge = charge

    @property
    def time(self):
        """Gets the time of this VehicleDeparture.  # noqa: E501

        Expected time of departure of the event. Format is **RFC 3339**, section 5.6 as defined by `date-time`.  # noqa: E501

        :return: The time of this VehicleDeparture.  # noqa: E501
        :rtype: AllOfVehicleDepartureTime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this VehicleDeparture.

        Expected time of departure of the event. Format is **RFC 3339**, section 5.6 as defined by `date-time`.  # noqa: E501

        :param time: The time of this VehicleDeparture.  # noqa: E501
        :type: AllOfVehicleDepartureTime
        """

        self._time = time

    @property
    def place(self):
        """Gets the place of this VehicleDeparture.  # noqa: E501


        :return: The place of this VehicleDeparture.  # noqa: E501
        :rtype: VehiclePlace
        """
        return self._place

    @place.setter
    def place(self, place):
        """Sets the place of this VehicleDeparture.


        :param place: The place of this VehicleDeparture.  # noqa: E501
        :type: VehiclePlace
        """
        if place is None:
            raise ValueError("Invalid value for `place`, must not be `None`")  # noqa: E501

        self._place = place

    @property
    def charge(self):
        """Gets the charge of this VehicleDeparture.  # noqa: E501

        Vehicle battery charge (in kWh).  # noqa: E501

        :return: The charge of this VehicleDeparture.  # noqa: E501
        :rtype: float
        """
        return self._charge

    @charge.setter
    def charge(self, charge):
        """Sets the charge of this VehicleDeparture.

        Vehicle battery charge (in kWh).  # noqa: E501

        :param charge: The charge of this VehicleDeparture.  # noqa: E501
        :type: float
        """

        self._charge = charge

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VehicleDeparture, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VehicleDeparture):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
