# coding: utf-8

"""
    Public Transit API

    Public Transit is a set of three REST APIs that provides public transit routing information and public transit stations information available within an area or for a given station.   # noqa: E501

    OpenAPI spec version: 8.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VersionResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'api_version': 'str',
        'service_version': 'str',
        'data_versions': 'list[DataVersion]'
    }

    attribute_map = {
        'api_version': 'apiVersion',
        'service_version': 'serviceVersion',
        'data_versions': 'dataVersions'
    }

    def __init__(self, api_version=None, service_version=None, data_versions=None):  # noqa: E501
        """VersionResponse - a model defined in Swagger"""  # noqa: E501
        self._api_version = None
        self._service_version = None
        self._data_versions = None
        self.discriminator = None
        self.api_version = api_version
        if service_version is not None:
            self.service_version = service_version
        if data_versions is not None:
            self.data_versions = data_versions

    @property
    def api_version(self):
        """Gets the api_version of this VersionResponse.  # noqa: E501

        The current version of the API.  # noqa: E501

        :return: The api_version of this VersionResponse.  # noqa: E501
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version):
        """Sets the api_version of this VersionResponse.

        The current version of the API.  # noqa: E501

        :param api_version: The api_version of this VersionResponse.  # noqa: E501
        :type: str
        """
        if api_version is None:
            raise ValueError("Invalid value for `api_version`, must not be `None`")  # noqa: E501

        self._api_version = api_version

    @property
    def service_version(self):
        """Gets the service_version of this VersionResponse.  # noqa: E501

        The current version of the service.  # noqa: E501

        :return: The service_version of this VersionResponse.  # noqa: E501
        :rtype: str
        """
        return self._service_version

    @service_version.setter
    def service_version(self, service_version):
        """Sets the service_version of this VersionResponse.

        The current version of the service.  # noqa: E501

        :param service_version: The service_version of this VersionResponse.  # noqa: E501
        :type: str
        """

        self._service_version = service_version

    @property
    def data_versions(self):
        """Gets the data_versions of this VersionResponse.  # noqa: E501

        Returns the versions of data sets used by the service.  # noqa: E501

        :return: The data_versions of this VersionResponse.  # noqa: E501
        :rtype: list[DataVersion]
        """
        return self._data_versions

    @data_versions.setter
    def data_versions(self, data_versions):
        """Sets the data_versions of this VersionResponse.

        Returns the versions of data sets used by the service.  # noqa: E501

        :param data_versions: The data_versions of this VersionResponse.  # noqa: E501
        :type: list[DataVersion]
        """

        self._data_versions = data_versions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VersionResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VersionResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
